/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package meetingmanagergui;

import BloggManager.BloggService;
import DB.EmployeeDB;
import DB.PostDB;
import Models.Employee;
import Models.ForskningsInlagg;
import Models.IEmployee;
import Models.IPost;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import org.firebirdsql.jdbc.FBEscapedFunctionHelper;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class RemoveResearchPost extends javax.swing.JFrame {

    private IPost _postService = new BloggService (new PostDB());
    ArrayList<ForskningsInlagg> list = new ArrayList<>();
    
    private Employee employee;
    private IEmployee _employeService = new BloggService(new EmployeeDB());
    
    
    
    /**
     * Creates new form RemoveMeeting
     */
    
    public RemoveResearchPost() {
        initComponents();
    }
    
    public RemoveResearchPost(Employee e) {
        this.employee = e;
        initComponents();
        initTable();
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDelete = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblForskningsInlagg = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnDelete.setText("Ta bort");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        tblForskningsInlagg.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1"
            }
        ));
        jScrollPane2.setViewportView(tblForskningsInlagg);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(btnDelete)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDelete)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        
        int col = tblForskningsInlagg.getSelectedColumn();
        int row = tblForskningsInlagg.getSelectedRow();       
        var researchRow = tblForskningsInlagg.getValueAt(row, col);
        var researchName = researchRow.toString();
        
        _postService.deleteResearchPost(researchName);
        
        clearTable();
        initTable(); 
        
        JOptionPane.showMessageDialog(null, "Ditt inlägg har tagitsbort");
       
        
    }//GEN-LAST:event_btnDeleteActionPerformed

    
    private void initTable(){
        DefaultTableModel model = (DefaultTableModel) tblForskningsInlagg.getModel();
        
        list = _postService.getAllResearchPosts();
        Object rowData[] = new Object[2];
        for(int i = 0; i < list.size(); i++)
        {
            if(list.get(i).getUsername().equals(employee.getUsername())){
            rowData[0] = list.get(i).getRubrik();
            model.addRow(rowData);
            }
        }
    }
    
    private void clearTable(){
        DefaultTableModel model = (DefaultTableModel) tblForskningsInlagg.getModel();
        model.setRowCount(0);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RemoveResearchPost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RemoveResearchPost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RemoveResearchPost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RemoveResearchPost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RemoveResearchPost().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblForskningsInlagg;
    // End of variables declaration//GEN-END:variables
}
